spring:
  datasource:
    url: jdbc:h2:mem:customerdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///customerdb
    username: sa
    password:

server:
  port: 8081

jwt:
  secret: "your-very-secure-secret-key" # Change this in production
  expiration: 86400000 # 24 hours in milliseconds