server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///productdb
    username: sa
    password: